[package]
name = "reportbook"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.10"
installed = "=0.1.0"
cpuid = "0.1.1"
whoami = "1.5.1"
machine-info = "1.0.6"
ureq = { version = "2.9.6", default-features = false, features = ["native-tls"] }
native-tls = "0.2.11"
