[package]
name = "fullreport"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.10"
installed = "=0.1.0"
titlecase = "3.0.0"
cpuid = "0.1.1"
reqwest = "0.12.3"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }